name: Build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  release:
    types:
      - published
jobs:
  build:
    name: Conda ${{ matrix.python-version }} - ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7','3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      shell: bash -l {0}
      run: |
          pip install --upgrade numpy lazperf flake8 pytest

    - name: Install
      shell: bash -l {0}
      run: |
        pip install -e .
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        flake8 --statistics laspy
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pip install pytest
        python -m pytest --ignore misc




  collect-artifacts:
    name: Package and push release

    needs: [build]

    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - name: Source
        shell: bash -l {0}
        run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install setuptools numpy flake8 pytest wheel lazperf
            export PATH=$PATH:/home/runner/.local/bin
            python3 setup.py sdist

      - uses: pypa/gh-action-pypi-publish@master
        name: Publish package
        if: github.event_name == 'release' && github.event.action == 'published'
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
          packages_dir: ./dist
